version: "3.8"

services:
  ctf_easy:
    image: ubuntu:20.04
    container_name: ctf_easy
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./easy:/var/www/html
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["/bin/bash", "-c", "apt update && apt install -y apache2 php libapache2-mod-php tzdata && echo 'ServerName localhost' >> /etc/apache2/apache2.conf && service apache2 start && tail -f /dev/null"]

  ctf_medium:
    image: debian:11
    container_name: ctf_medium
    ports:
      - "8082:80"
      - "2222:22"
    restart: always
    volumes:
      - ./medium:/var/www/html
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["/bin/bash", "-c", "apt update && apt install -y apache2 php libapache2-mod-php mariadb-server sudo openssh-server tzdata && echo 'ServerName localhost' >> /etc/apache2/apache2.conf && service apache2 start && service ssh start && tail -f /dev/null"]

  ctf_hard:
    image: kalilinux/kali-rolling
    container_name: ctf_hard
    ports:
      - "8083:80"
      - "2223:22"
    restart: always
    volumes:
      - ./hard:/var/www/html
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["/bin/bash", "-c", "apt update && apt install -y apache2 php libapache2-mod-php openssh-server tzdata && echo 'ServerName localhost' >> /etc/apache2/apache2.conf && service apache2 start && service ssh start && tail -f /dev/null"]