version: "3.8"

services:
  ctf_easy:
    build: ./easy
    container_name: ctf_easy
    ports:
      - "8081:80"
    restart: always

  ctf_medium:
    build: ./medium
    container_name: ctf_medium
    ports:
      - "8082:80"
      - "2222:22"
    restart: always

  ctf_hard:
    build: ./hard
    container_name: ctf_hard
    ports:
      - "8083:80"
      - "2223:22"
    restart: always

  ctf_pwn_one:
    build: ./PWN
    container_name: ctf_pwn_one
    ports:
      - "8084:80"
    restart: always
    volumes:
      - ./PWN:/app
    command: ["/bin/bash", "-c", "cd /app && ./pwn1"]